name: Build base image

on:
  workflow_dispatch:
    inputs:
      cmake_version:
        type: string
        required: false
        default: 3.17.0
      gcc_version:
        type: string
        required: false
        default: 9
      ubuntu_version:
        type: string
        required: false
        default: 20.04
      madness_version:
        type: string
        required: false
        default: 997e8b458c4234fb6c8c2781a5df59cb14b7e700
      catch2_version:
        type: string
        required: false
        default: 2.13.8
      spdlog_version:
        type: string
        required: false
        default: ad0e89cbfb4d0c1ce4d097e134eb7be67baebb36
      cereal_version:
        type: string
        required: false
        default: 1.3.0

jobs:
  build-image-gcc-cmake:
    uses: NWChemEx-CI-test/.github/.github/workflows/base_image_gcc-cmake.yaml@master
    with:
      cmake_version: ${{ inputs.cmake_version }}
      gcc_version: ${{ inputs.gcc_version }}
      ubuntu_version: ${{ inputs.ubuntu_version }}
    secrets: inherit

  build-base-image:
    runs-on: ubuntu-latest
    needs: build-image-gcc-cmake
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Install MADNESS and MPI
        uses: NWChemEx-CI-test/.github/actions/install_one@master
        with:
          madness_version: ${{ inputs.madness_version }}
          package_name: madness
          parent_image_name: ghcr.io/nwchemex-ci-test/base-cmake
      - name: Install spdlog
        uses: NWChemEx-CI-test/.github/actions/install_one@master
        with:
          spdlog_version: ${{ inputs.spdlog_version }}
          package_name: spdlog
          parent_image_name: base-madness
      - name: Install cereal
        uses: NWChemEx-CI-test/.github/actions/install_one@master
        with:
          cereal_version: ${{ inputs.cereal_version }}
          package_name: cereal
          parent_image_name: base-spdlog
      - name: Install catch2
        uses: NWChemEx-CI-test/.github/actions/install_one@master
        with:
          catch2_version: ${{ inputs.catch2_version }}
          package_name: catch2
          parent_image_name: base-catch2
      - name: Push the base image
        env:
          tmp_image_name: base-catch2
          base_image_name: ghcr.io/nwchemex-ci-test/base-parallelzone:latest
        run: |
          docker tag ${{env.tmp_image_name}}:latest ${{env.base_image_name}}:latest
          docker push ${{env.base_image_name}}:latest
