name: Building the ParallelZone documentation with the basic Docker image
on:
  push:
    branches: [ master ]
jobs:
  container-building-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yzhang-23/build_parallelzone_doc:v1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PAT }}
    steps:
      - name: checkout action
        uses: actions/checkout@v3
        with:
          repository: yzhang-23/.github 
          path: yzhang-23/.github
            #- name: Check out NWChemEx/.github repo
            #  shell: bash
            #  run: git clone https://github.com/NWChemEx-Project/.github.git
            #- name: Check the path
            #  run: |
            #    cd NWChemEx-Project/.github
            #    pwd
            #    ls -lrtd *
      - name: Install python tools
        run: apt-get install python3.8-distutils
      - name: Build documentation
        uses: yzhang-23/.github/actions/build_docs@master
        with:
          target: ${{inputs.target}}
          skip_doxygen: ${{inputs.skip_doxygen}}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{secrets.DOCKER_PAT}}
          publish_dir: ./docs/build/html
