name: Build and test with dev

on:
  pull_request:
    branches:
      - dev

jobs:
  docker-file-changes:
    runs-on: ubuntu-latest
    outputs:
      build_dockfile: ${{ steps.changes.outputs.bdfile }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          bdfile:
            - 'build.Dockerfile'

  update-building-image:
    needs: docker-file-changes
    if: ${{ needs.docker-file-changes.outputs.build_dockfile == 'true' }}
    uses: NWChemEx-CI-test/.github/.github/workflows/update_building_image_tmpl.yaml@master
    with:
      repo_name: ParallelZone
    secrets: inherit

  build-update-repo_dispatch:
    runs-on: ubuntu-latest
    needs: update-building-image
    strategy:
      matrix:
        repos: [Utilities, PluginPlay]
    if: ${{ needs.docker-file-changes.outputs.build_dockfile == 'true' }}
    steps:
      - name: send build update dispatch
        uses: NWChemEx-CI-test/.github/actions/repo_dispatch@master
        with:
          to_repo: ${{ matrix.repos }}
          type: build_update
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          from_repo: ParallelZone
          initial_repo: ParallelZone

  build_update_check:
    runs-on: ubuntu-latest
    needs: docker-file-changes
    outputs:
      bi_check: ${{ steps.building-image-update.outputs.tag }}
    steps:
      - name: Check if the building image has been updated
        id: building-image-update
        run: |
          if [ ${{ needs.docker-file-changes.outputs.build_dockfile == 'true' }} ]; then
             tag="test"
          else
             tag="stable"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
          #echo "tag=$tag" > tag.dat
          #- name: Upload tag as an artifact
          #  uses: actions/upload-artifact@v3
          #  with:
          #    name: tag-artifact
          #    path: tag.dat

  build-with-gcc:
    uses: NWChemEx-CI-test/.github/.github/workflows/build_test-dev_tmpl.yaml@master
    needs: [update-building-image, build_update_check]
    if: always() && (needs.update-building-image.result == 'success' || needs.update-building-image.result == 'skipped')
    with: 
      repo: Utilities
      clang-build: false
      gcc-build: true
      ninja_build: true
      test: true
      integration_test: false
      install: false
      build_image_tag: ${{ needs.build_update_check.outputs.bi_check }}
    secrets: inherit 
    #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
    #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
  
  merge-pr-to-dev:
    runs-on: ubuntu-latest
    needs: build-with-gcc
    steps:
      - name: merge pr to dev
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.DOCKER_PAT }}"
          MERGE_LABELS: ""

# are we working on the dev branch now? check!
  Integration_test:
    uses: NWChemEx-CI-test/.github/.github/workflows/build_test-dev_tmpl.yaml@master
    needs: merge-pr-to-dev
    with:
      repo: ParallelZone
      clang-build: false
      gcc-build: true
      ninja_build: true
      test: true
      integration_test: true
      install: true
      build_image_tag: test
      ref: dev
    secrets: inherit

# Update other repos
  Update-repo_dispatch:
    needs: Integration_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: [TensorWrapper, PluginPlay]
    steps:
      - uses: NWChemEx-CI-test/.github/actions/repo_dispatch@master
        with:
          to_repo: ${{ matrix.repos }}
          type: build_update
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          from_repo: ParallelZone
          initial_repo: ParallelZone
