name: Building the Docker image containing the basic tools for building ParallelZone
on:
  push:
    paths:
      - .github/workflows/Docker/**

jobs:
  docker-image-build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Build the docker image and push
      run: |
        docker build -t ghcr.io/yzhang-23/build_parallelzone:v4 -f Docker/ParallelZone.Dockerfile .
        docker push ghcr.io/yzhang-23/build_parallelzone:v4
