name: Build and Deploy Documentation with Docker Image
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: yzhang-23/.github/.github/workflows/image-deploy_docs_tmpl.yaml@master
    with:
      target: parallelzone_cxx_api
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
